const lakes = {
    tims_ford_lake: "Tim's Ford Lake",
    center_hill_lake: 'Center Hill Lake',
    dale_hollow_lake: 'Dale Hollow Lake',
    normandy_lake: 'Normandy Lake',
    boone_lake: 'Boone Lake',
    douglas_lake: 'Douglas Lake',
    tellico_lake: 'Tellico Lake',
    norris_lake: 'Norris Lake',
    watauga_lake: 'Watauga Lake',
    reelfoot_lake: 'Reelfoot Lake',
    south_holston_lake: 'South Holston Lake',
    cherokee_lake: 'Cherokee Lake',
    percy_priest_lake: 'Percy Priest Lake',
};

const marinas = {
    tims_ford_lake: {
        tims_ford_marina: "Tim's Ford Marina",
        lakeview_marina: "Lakeview Marina",
        holiday_landing_marina: 'Holiday Landing Marina',
        tims_ford_state_park: "Tim's Ford State Park",
        twin_creeks_marina: 'Twin Creeks Marina',
    },
    center_hill_lake: {
        center_hill_marina: 'Center Hill Marina',
        hurrican_marina: 'Hurrican Marina',
        edgar_evins_marina: 'Edgar Evins Marina',
        hidden_harbor_marina: 'Hidden Harbor Marina',
        silgo_marina: 'Silgo Marina',
        four_seasons_marina: 'Four Seasons Marina',
        cookeville_boat_dock: 'Cookeville Boat Dock',
        horseshoe_bend_marina: 'Horseshoe Bend Marina',
        cottens_marina: "Cotten's Marina",
        smithmill_marina: 'Smithmill Marina',
    },
    dale_hollow_lake: {
        east_port_marina: 'East Port Marina',
        sunset_marina: 'Sunset Marina',
        willow_grove_marina: 'Willow Grove Marina',
    },
    normandy_lake: {
        firelake_boat_ramp: 'Firelake Boat Ramp',
        barton_springs_boat_ramp: 'Barton Springs Boat Ramp',
        dement_bridge_boat_ramp: 'Dement Bride Boat Ramp',
    },
    boone_lake: {
        boone_lake_marina: 'Boone Lake Marina',
        davis_marina: 'Davis Marina',
        jays_boat_dock: "Jay's Boat Dock",
        carefree_boat_club: 'Carefree Boat Club',
        serenity_cove_marina: 'Serenity Cove Marina',
        lakeview_marina: 'Lakeview Marina',
    },
    douglas_lake: {
        douglas_lake_marina: 'Douglas Lake Marina',
        mountain_cove_marina: 'Mountain Cove Marina',
        swanns_marina: "Swann's Marina",
        lighthouse_marina: 'Lighthouse Marina',
        indian_creek_dock: 'Indian Creek Dock',
    },
    tellico_lake: {
        tellico_marina: 'Tellico Marina',
        sequoya_lake_tellico_marina: 'Sequoya Lake Tellico Marina',
        windriver_marina: 'Windriver Marina',
        fort_loudin_marina: 'Fort Loudin Marina',
        chato_marina: 'Chato Marina',
        concord_marina: 'Concord Marina',
        louisville_marina: 'Lousiville Marina',
        fox_road_marina: 'Fox Road Marina',
        pjs_landing_marina: "PJ's Landing Marina",
        long_island_marina: 'Long Island Marina',
        volunteer_landing_marina: 'Volunteer Landing Marina',
        caney_creek_marina: 'Caney Creek Marina',
        indian_river_marina: 'Indian River Marina',
        stardust_marina: 'Stardust Marina',
        norris_dam_marina: 'Norris Dam Marina',
        twin_cove_marina: 'Twin Cove Marina',
        sugar_hollow_marina: 'Sugar Hollow Marina',
        flat_hollow_marina: 'Flat Hollow Marina',
        whitman_hollow_marina: 'Whitman Hollow Marina',
        swanns_marina: "Swann's Marina",
        beach_island_marina: 'Beach Island Marina',
        huffs_german_creek_marina: "Huff's German Creek Marina",
        hickory_star_marina: 'Hickory Star Marina',
        aqua_knox_marina: 'Aqua Knox Marina',
    },
    norris_lake: {
        norris_lake_marina: 'Norris Lakw Marina',
        norris_landing_marina: 'Norris Landing Marina',
        sequoya_marina: 'Sequoya Marina',
        stardust_marina: 'Stardust Marina',
        mountain_lake_marina: 'Mountain Lake Marina',
        waterside_marina: 'Waterside Marina',
        whitman_hollow_boat_dock: 'Whitman Hollow Boat Dock',
        sugar_hollow_marina: 'Sugar Hollow Marina',
        flat_hollow_marina: 'Flat Hollow Marina',
        indian_river_marina: 'Indian River Marina',
        straight_creek_boat_dock: 'Straight Creek Boat Dock',
        hickory_star_resort: 'Hickory Star Resort',
        beach_island_resort_and_marina: 'Beach Island Resort & Marina',
        kilgores_union_co_boat_dock: "Kilgore's Union Co Boat Dock",
        blue_springs_hollow_boat_dock: 'Blue Springs Hollow Boat Dock',
        cedar_grove_marina: 'Cedar Grove Marina',        
    },
    watauga_lake: {
        fish_springs_marina: 'Fish Springs Marina',
        lakeshore_marina: 'Lakeshore Marina',
        cove_ridge_marina: 'Cove Ridge Marina',
        pioneer_landing: 'Pioneer Landing',
    },
    reelfoot_lake: {
        reelfoot_lake_marina: 'Reelfoort Lake Marina',
        blue_bank_marina: 'Blue Bank Marina',
        bos_landing: "Bo's Landing",
    },
    south_holston_lake: {
        laurel_marina: 'Laurel Marina',
        lakeview_dock: 'Lakeview Dock',
        sportsman_marina: 'Sportsman Marina',
        painter_creek_marina: 'Painter Creek Marina',
    },
    cherokee_lake: {
        hamblen_county_marina: 'Hamblen County Marina',
        lakeside_marina: 'Lakeside Marina',
    },
    percy_priest_lake: {
        percy_priest_marina: 'Percy Priest Marina',
        elm_hill_marina: 'Elm Hill Marina',
        hamilton_creek_marina: 'Hamilton Creek Marina',
        fate_sanders_marian: 'Fate Sanders Marina',
        blue_turtle_bay_marina: 'Blue Turtle Bay Marina',
        creekwood_marina: 'Creekwood Marina',
        cedar_creek_marina: 'Cedar Creek Marina',
        drakes_marina: 'Drakes Marina',
        anchor_high_marina: 'Anchor High Marina',
        gallatin_marina: 'Gallatin Marina',
        rock_habor_marina: 'Rock Harbor Marina',
        harpeth_shoals_marina: 'Harpeth Shoals Marina',
    },
};

const mapConfigs = {
    dale_hollow_lake: {
        center: {
            lat: 36.59554836583276,
            lng: -85.26669759121096,
        },
        zoom: 10.9,
    },
};

export default { lakes, marinas, mapConfigs };